Version Check: true
Faction Nameplate:
  Prefix:
    Enabled: false
    Format: '%f'
  Suffix:
    Enabled: false
    Format: '%f'
Teleport:
  Enabled: false
  Cooldown: 0
  Types:
    - ENEMY
  Enemy Alert Message: '&4An enemy has teleported into your land!'
  Neutral Alert Message: '&4Someone has teleported into your land!'
  Ally Alert Message: '&4An ally has teleported into your land!'
  None Alert Message: '&4A player with no faction has teleported into your land!'
Move:
  Enabled: false
  Cooldown: 0
  Types:
    - ENEMY
  Enemy Alert Message: '&4An enemy has entered your land!'
  Neutral Alert Message: '&4Someone has entered your land!'
  Ally Alert Message: '&4An ally has entered your land!'
  None Alert Message: '&4A player with no faction has entered your land!'
Combat:
  Enabled: false
  Cooldown: 10
  Types:
    - ENEMY
  Receivers:
    - LEADER
    - OFFICER
    - RECRUIT
    - MEMBER
  Enemy Alert Message: '&4%n from %f has engaged in combat with %m'
  Neutral Alert Message: '&4%n from %f has engaged in combat with %m'
  Ally Alert Message: '&4%n from %f has engaged in combat with %m'
  None Alert Message: '&4%n has engaged in combat with %m'
Member Death:
  Enabled: false
  Cooldown: 0
  Member Alert Message: '&4%n has died!'