Faction Nameplate:
  Prefix:
    Enabled: false
    Format: '%f'
  Suffix:
    Enabled: false
    Format: '%f'
Teleport:
  Enabled: true
  Cooldown: 0
  Types:
    - ENEMY
  Enemy Alert Message: '&4An enemy has teleported into your land!'
  Neutral Alert Message: '&4Someone has teleported into your land!'
  Ally Alert Message: '&4An ally has teleported into your land!'
Move:
  Enabled: false
  Cooldown: 0
  Types:
    - ENEMY
  Enemy Alert Message: '&4An enemy has entered your land!'
  Neutral Alert Message: '&4Someone has entered your land!'
  Ally Alert Message: '&4An ally has entered your land!'
Member Death:
  Enabled: false
  Cooldown: 0
  Member Alert Message: '&4%n has died!'