name: FactionAlert
main: me.superckl.factionalert.FactionAlert
version: 0.51-Alpha
author: superckl
depend: [Factions]
commands:
  factionalert:
    description: Base command for FactionAlert commands
    aliases: [fa, falerts, falert]
